### ISSUE TITLE
Error running demo

### ISSUE THREAD

**Issue by kahnchana** [wentaoyuan/RoboPoint#1]
Really appreciate sharing the code for this interesting project. I am trying to explore your pretrained models using the code in this repo and facing some issues.

In particular, I am trying to launch the demo following scripts [here](https://github.com/wentaoyuan/RoboPoint?tab=readme-ov-file#gradio-web-ui). 

After launching all three, the gradio web server gives the following error when I load the webpage:

```
2024-10-03 13:10:22 | ERROR | stderr | Traceback (most recent call last):
2024-10-03 13:10:22 | ERROR | stderr |   File "/home/kanchana/miniconda3/envs/robopoint/lib/python3.10/site-packages/pydantic/type_adapter.py", line 270, in _init_core_attrs
2024-10-03 13:10:22 | ERROR | stderr |     self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
2024-10-03 13:10:22 | ERROR | stderr |   File "/home/kanchana/miniconda3/envs/robopoint/lib/python3.10/site-packages/pydantic/type_adapter.py", line 112, in _getattr_no_parents
2024-10-03 13:10:22 | ERROR | stderr |     raise AttributeError(attribute)
2024-10-03 13:10:22 | ERROR | stderr | AttributeError: __pydantic_core_schema__
```

**Comment by jiafei1224** [comment]
Ya there is some issue with the version for gradio. Have fun 'Pointing'!
